In [1]:
import torch
import numpy as np

In [2]:
print("Torch version:", torch.version.__version__)
print("Numpy version:", np.version.__version__)

Torch version: 2.2.0+cpu
Numpy version: 1.25.2


## Using Tensors

### Scalars

The atomic value or smallest unit of information that can be stored inside a tensor object. These do not have any dimensions as they are pure values. You can relate them to a leaf nodes when considering a expression tree.

In [3]:
val = 10
scalar = torch.tensor(val)
scalar

tensor(10)

In [4]:
# Number of dimensions
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
torch.is_tensor(val)

False

In [7]:
torch.is_tensor(scalar)

True

### Vectors

A tensor with one-dimensional array of numbers form a vector datatype. 

In [8]:
x = list(range(0, 20, 2))
x

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
vector = torch.tensor(x)
vector

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# Number of dimensions
vector.ndim

1

In [11]:
vector.shape

torch.Size([10])

In [12]:
torch.is_tensor(vector)

True

### Matrix

A 2-dimensional arrangement of scalars in row and column order forms a matrix.

In [13]:
matrix = torch.tensor([
    [4, 5],
    [10, 10]
])
matrix

tensor([[ 4,  5],
        [10, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 2])

In [16]:
torch.is_tensor(matrix)

True

### Tensor

A multi-dimensional collection of elements is called a tensor.

In [17]:
tensor = torch.tensor([[
    [1, 2],
    [4, 5],
    [7, 8]
]])

In [18]:
tensor.ndim

3

In [19]:
tensor.shape

torch.Size([1, 3, 2])

In [20]:
# Tensor Data type
tensor.dtype

torch.int64

In [21]:
tensor.device

device(type='cpu')

In [22]:
torch.is_tensor(tensor)

True

## Random Tensors and Operations

In [23]:
y = torch.randn(1, 2, 3, 4, 5)
y.shape, y.dtype, y.ndim

(torch.Size([1, 2, 3, 4, 5]), torch.float32, 5)

In [24]:
# Calculate number of elements
y.numel()

120

In [25]:
# Zero tensor
zeros = torch.zeros([1,3])
zeros, zeros.shape, zeros.numel(), zeros.ndim

(tensor([[0., 0., 0.]]), torch.Size([1, 3]), 3, 2)

In [26]:
# Identity tensor - Diagonal matrix of 1's
identity = torch.eye(3) # Input is single parameter defining the size of the resultant square matrix
identity, identity.shape, identity.numel(), identity.ndim

(tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 torch.Size([3, 3]),
 9,
 2)

In [27]:
# convert numpy array to torch tensor
np_arr = np.array(x)
trch_converted = torch.from_numpy(np_arr)

np_arr, trch_converted

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=torch.int32))

In [28]:
# Linear space and points between the linear space can be created using tensor
torch.linspace(2, 10, steps=5)

tensor([ 2.,  4.,  6.,  8., 10.])

In [29]:
# logarithmic spacing can also be created
torch.logspace(-10, 10, steps=15)

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1969e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

In [30]:
# One's array
torch.ones([1, 2, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [31]:
torch.ones(1, 2, 3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [32]:
# Generating random number from uniform distribution between the values 0 and 1, with mean=0 and variance=1
torch.rand(10)

tensor([0.2943, 0.8766, 0.1220, 0.4201, 0.7140, 0.1634, 0.0093, 0.2379, 0.1421,
        0.7370])

In [33]:
# permutation: select values from a range
torch.randperm(10)

tensor([2, 3, 7, 0, 6, 1, 4, 5, 9, 8])

In [34]:
# range function
torch.arange(2, 10, 2)

tensor([2, 4, 6, 8])

In [35]:
# to find index of the minimum and maximum value in tensor
d = torch.randn(2, 5) * 10
print(d, d.ndim)

print("Minimum Value:", torch.argmin(d, dim=0))
print("Maximum Value:", torch.argmax(d, dim=0))

print("Minimum Value:", torch.argmin(d, dim=1))
print("Maximum Value:", torch.argmax(d, dim=1))


tensor([[16.3525, 11.5621, 10.7333, -6.5413, -0.4173],
        [ 6.0855, -8.0752, -1.6694, -1.9748,  2.3242]]) 2
Minimum Value: tensor([1, 1, 1, 0, 0])
Maximum Value: tensor([0, 0, 0, 1, 1])
Minimum Value: tensor([3, 1])
Maximum Value: tensor([0, 0])


In [36]:
a = torch.ones([1, 4])
b = torch.ones([1, 4]) * 2

c = torch.concat([a, b])

print(f"a ({a.shape}) = ", a)
print(f"b ({b.shape}) = ", b)
print(f"c ({c.shape}) = ", c)

a (torch.Size([1, 4])) =  tensor([[1., 1., 1., 1.]])
b (torch.Size([1, 4])) =  tensor([[2., 2., 2., 2.]])
c (torch.Size([2, 4])) =  tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.]])


In [37]:
# split tensor into given number of total chunks
torch.arange(11).chunk(4)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10]))

In [53]:
# split tensor with each sub-tensor of given chunk size
torch.arange(11).split(4)

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10]))

In [38]:
# Takes element from one array and places them based on another's array input (Long Tensor)
torch.gather(
    torch.Tensor([[11, 12], [23,24]]), 1,
    torch.LongTensor([[0,0],[1,0]])
)

tensor([[11., 11.],
        [24., 23.]])

In [50]:
# Change shape of tensor
a = torch.arange(16).reshape((4, 4))
print("a=", a, "\n")

# Selecting specific rows (axis = 0)
idxs = torch.LongTensor([0, 2])
print(torch.index_select(a, 0, idxs), "\n")

# Selecting columns (axis = 1)
idxs = torch.LongTensor([0, 2])
print(torch.index_select(a, 1, idxs), "\n")


a= tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) 

tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]]) 

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]]) 



In [52]:
# Get list of indices with non-zero values
torch.nonzero(torch.tensor([10, 0, 23, 0, -10, -0])) 

tensor([[0],
        [2],
        [4]])

In [54]:
torch.Size([3, 2, 4])

torch.Size([3, 2, 4])

In [60]:
# Transpose a tensor
a = torch.arange(16).reshape((4, 4))
print(a, "\n")

# Transpose rows and columns
print(a.t(),"\n")

# Transpose specific axis
print(a.transpose(1, 0))


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) 

tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]]) 

tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])


In [61]:
# Delete dimension
a = torch.arange(16).reshape((4, 4))
print(a, "\n")

print(torch.unbind(a, 1))

print(torch.unbind(a))


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) 

(tensor([ 0,  4,  8, 12]), tensor([ 1,  5,  9, 13]), tensor([ 2,  6, 10, 14]), tensor([ 3,  7, 11, 15]))
(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]), tensor([12, 13, 14, 15]))


## Mathematical Operations

In [64]:
# absolute value
print(torch.abs(torch.tensor([1.09, 2.56777, 3.99999999999999999, -1.2999999999])))

print(torch.abs(torch.FloatTensor([1.09, 2.56777, 3.99999999999999999, -1.2999999999])))


tensor([1.0900, 2.5678, 4.0000, 1.3000])
tensor([1.0900, 2.5678, 4.0000, 1.3000])


In [70]:
# scalar addition   
print(torch.eye(2, 2).add(9))       

tensor([[10.,  9.],
        [ 9., 10.]])


In [72]:
# scalar multiplication
print(torch.eye(2, 2).mul(9))

tensor([[9., 0.],
        [0., 9.]])


In [78]:
# How to represent the below equation
# y = mx + c

x = torch.randn(2, 2)
bias = torch.randn(1)
slope = 0.74

print("slope m = ", slope)
print("input x = ", x)

print("bias c = ", bias)

print("mx + c =", slope * x + bias)

print("mx + c =", torch.add(torch.mul(x, slope), bias))



slope m =  0.74
input x =  tensor([[1.5075, 0.1593],
        [0.0700, 0.6625]])
bias c =  tensor([1.2036])
mx + c = tensor([[2.3191, 1.3215],
        [1.2554, 1.6939]])
mx + c = tensor([[2.3191, 1.3215],
        [1.2554, 1.6939]])


In [81]:
# Element wise matrix multiplication
i = torch.eye(2, 2)

print(i * i)

print(i @ i)

print(torch.matmul(i, i))

tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])


In [83]:
# ceil and floor functions
torch.manual_seed(1234)
print(torch.ceil(torch.randn(5, 5)))

torch.manual_seed(1234)
print(torch.floor(torch.randn(5, 5)))


tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])
tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])


In [85]:
# clamp function: limit min and max value range of a tensor
torch.clamp(
    torch.tensor([[1, 2, 3], [0, -100, 1], [100000, 12, 4]]),
    min = -10, 
    max = 10
)

tensor([[  1,   2,   3],
        [  0, -10,   1],
        [ 10,  10,   4]])

In [88]:
# Scalar Division
print(torch.div(
    torch.tensor([2, 4, 6, 8]),
    2
)
)

print(torch.tensor([2, 4, 6, 8, 10]) / 2.0)

tensor([1., 2., 3., 4.])
tensor([1., 2., 3., 4., 5.])


In [90]:
# Exponential of tensor. (e ^ tensor)
torch.exp(torch.arange(3))

tensor([1.0000, 2.7183, 7.3891])

In [91]:
# extract fractional part of tensor
torch.frac(torch.tensor([0.9, 0.007, -0.003, 100.23]))

tensor([ 0.9000,  0.0070, -0.0030,  0.2300])

In [4]:
x = torch.tensor([-1.5, 1, 0, 23, 2.4])

# logs of negative NaN
print(torch.log(x))

print(torch.pow(x, 2))

tensor([   nan, 0.0000,   -inf, 3.1355, 0.8755])
tensor([  2.2500,   1.0000,   0.0000, 529.0000,   5.7600])


In [6]:
x = torch.tensor([[1.3145, -0.3199], [0.1739, 0.0347]])

print(np.round(x))

print(torch.round(x))

tensor([[1., -0.],
        [0., 0.]])
tensor([[1., -0.],
        [0., 0.]])


In [9]:
x = torch.randn(5) * 2
print(x)

print(torch.sigmoid(x))

print(torch.sqrt(x))

tensor([-2.5267, -3.6728,  4.2588, -0.3068, -3.8371])
tensor([0.0740, 0.0248, 0.9861, 0.4239, 0.0211])
tensor([   nan,    nan, 2.0637,    nan,    nan])


In [15]:
x = torch.arange(10, 100, 20)
print(x)

print("Max: ", x.max())
print("ArgMax: ", x.argmax())

print("Min: ", x.min()) # value
print("ArgMin: ", x.argmin()) # index
print("Sum: ", x.sum())



tensor([10, 30, 50, 70, 90])
Max:  tensor(90)
ArgMax:  tensor(4)
Min:  tensor(10)
ArgMin:  tensor(0)
Sum:  tensor(250)


In [21]:
a = torch.arange(5)
b = torch.arange(5)
print("Stack 1:", torch.stack([a, b]))
print("Stack 2:", torch.stack([a, b], dim=0))

print("Stack 3:", torch.stack([a, b], dim=1))

Stack 1: tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])
Stack 2: tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])
Stack 3: tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])


In [29]:
c = torch.arange(16).view(4, 4)
print("C: ", c)

print("c[:, 0]:", c[:, 0])
print("c[0, :]:", c[0, :])
print("c[3, 2]:", c[3, 2])

C:  tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
c[:, 0]: tensor([ 0,  4,  8, 12])
c[0, :]: tensor([0, 1, 2, 3])
c[0, :]: tensor(14)


In [32]:
print("CUDA Avail:", torch.cuda.is_available())
print("Device Count:", torch.cuda.device_count())

CUDA Avaail: False
CUDA Avaail: 0


In [37]:
# x = torch.tensor([1, 2, 3], device='cpu')
# print(x)

# y = torch.tensor([1, 2, 3], device='cuda')
# print(y)